# Generated by Django 4.2.4 on 2023-08-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
    ]
