version: '3'
services:

  # Database
  db:
    container_name: url_shortener_db
    image: postgres:12
    env_file:
      - ../config/.env
    volumes:
      - db_volume_12:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

# External volume to persist db data
volumes:
  db_volume_12:
    external: true

networks:
  default:
    driver: bridge
