name: URL Shortener

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        ports:
          - "5432:5432"
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements/github_ci.txt

    - name: Set Pythonpath
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV

    - name: Test
      env:
        DEBUG: True
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        coverage run manage.py test src
        coverage json

    - name: Update Coverage Badge
      # GitHub actions: default branch variable
      # https://stackoverflow.com/questions/64781462/github-actions-default-branch-variable
      if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      uses: we-cli/coverage-badge-action@main
